#version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - oidc
    expose:
      - "8080"
    networks:
      - demo-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

#  envoy:
#    image: envoyproxy/envoy:v1.31.0
#    container_name: envoy
#    ports:
#      - "8092:8092"         # Angular calls this
#      - "9901:9901"         # Envoy admin
#    volumes:
#      - C:/Users/Rajendra Kumar V/Downloads/credentials-app/credentials-app/envoy.yml:/etc/envoy/envoy.yaml
#    depends_on:
#      - backend
#      - oidc
#    networks:
#      - demo-net

  oidc:
    build: ./mock-oidc
    container_name: mock-oidc
    ports:
      - "9000:9000"
    networks:
      - demo-net

networks:
  demo-net:
    driver: bridge
#  postgres:
#    image: postgres
#    container_name: user-credentials-postgres
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: userdb
#    ports:
#      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#
#volumes:
#  pgdata:
